package com.qisen.mts.common.model;

public enum MsgCode {
	
	/*
	 * common 
	 */
	COMMON_NO_EXIST("COMMON_NO_EXIST", "编号已存在"),
	COMMON_MOBILE_EXIST("COMMON_MOBILE_EXIST", "手机号码已存在"),
	COMMON_CREATE_FAILED("COMMON_CREATE_FAILED","创建失败"),
	COMMON_UPDATE_FAILED("COMMON_UPDATE_FAILED","更新失败"),
	COMMON_DELETE_FAILED("COMMON_DELETE_FAILED","删除失败"),
	COMMON_QUERY_FAILED("COMMON_QUERY_FAILED","查询失败"),
	/*
	 * 登录 
	 */
	ACCOUNT_NOT_EXIST("ACCOUNT_NOT_EXIST", "账号不存在"),
	ACCOUNT_PWD_NOT_MATCHED("ACCOUNT_PWD_NOT_MATCHED", "密码错误"),
	ACCOUNT_FORBIDDEN("ACCOUNT_FORBIDDEN", "账号被禁止登录"),
	ACCOUNT_UPDATE_TOKEN_ERROR("ACCOUNT_UPDATE_TOKEN_ERROR", "更新token异常"),
	/**
	 * 员工
	 */
	EMP_EDIT_NOORMOBILE_REPEAT("EMP_EDIT_NOORMOBILE_REPEAT","编号或者手机号码重复"),
	
	/**
	 * 会员
	 */
	MEMBER_EDIT_MOBILE_REPEAT("EMP_EDIT_NOORMOBILE_REPEAT","手机号码重复"),
	
	/**
	 * 套餐
	 */
	ITEM_PACK_NO_REPEAT("ITEM_PACK_NO_REPEAT","套餐编号重复"),
	/*
	 * 项目
	 */
	PRESENT_RULE_UPDATE_FAILD("PRESENT_RULE_UPDATE_FAILD", "充值赠送规则更新失败"),
	
	/*
	 * 库存
	 */
	NOT_ENOUGH_INVENTORY("NOT_ENOUGH_INVENTORY","商品库存不足"),
	NOT_ENOUGH_STOMONEY("NOT_ENOUGH_STOMONEY","商品出库金额不可大于库存金额"),
	INVENTORY_OR_BILL_DETAIL_UPDATE_FAILED("INVENTORY_OR_BILL_DETAIL_UPDATE_FAILED","库存/单据更新失败"),
	
	/*
	 * 收银
	 */
	CASH_BILL_CREATE_FAILED("CASH_BILL_CREATE_FAILED", "收银失败，创建单据失败"),
	CASH_BILLDETAIL_CREATE_FAILED("CASH_BILLDETAIL_CREATE_FAILED", "收银失败，创建单据明细失败"),
	CASH_EMP_CREATE_FAILED("CASH_EMP_CREATE_FAILED", "收银失败，创建服务、提成员工失败"),
	CASH_PAY_CREATE_FAILED("CASH_PAY_CREATE_FAILED", "收银失败，创建支付流水失败"),
	
	CASH_MEMBER_UPDATE_FAILED("CASH_MEMBER_UPDATE_FAILED", "收银失败，更新会员数据失败"),
	CASH_CARD_CREATE_FAILED("CASH_CARD_CREATE_FAILED", "收银失败，创建会员卡失败"),
	CASH_CARD_UPDATE_FAILED("CASH_CARD_UPDATE_FAILED", "收银失败，更新会员卡数据失败"),
	CASH_MEMITEM_CREATE_FAILED("CASH_MEMITEM_CREATE_FAILED", "收银失败，创建会员套餐账户失败"),
	CASH_MEMITEM_UPDATE_FAILED("CASH_MEMITEM_UPDATE_FAILED", "收银失败，更新会员套餐账户失败"),
	
	
	CASH_STOBILL_CREATE_FAILED("CASH_STOBILL_CREATE_FAILED", "收银失败，创建库存单据失败"),
	CASH_STOBILLDETAIL_CREATE_FAILED("CASH_STOBILLDETAIL_CREATE_FAILED", "收银失败，创建库存单据明细失败"),
	
	CASH_CARDNO_EXIST("CASH_CARDNO_EXIST", "收银失败，会员卡号已存在"),
	CASH_INVALID_CARD("CASH_INVALID_CARD", "收银失败，非法会员卡"),
	
	/*
	 * 单据
	 */
	BILL_CANCEL_UPDATE_MEMBER_FAILED("BILL_CANCEL_UPDATE_MEMBER_SROUCE_FAILED", "销单失败，更新会员数据失败"),
	BILL_CANCEL_UPDATE_CARD_FAILED("BILL_CANCEL_UPDATE_CARD_SROUCE_FAILED", "销单失败，更新会员卡数据失败"),
	BILL_CANCEL_NOT_ENOUGH_CARDFEE("BILL_CANCEL_NOT_ENOUGH_CARDFEE", "销单失败，卡账户余额不足"),
	BILL_CANCEL_UPDATE_MEMITEM_FAILED("BILL_CANCEL_UPDATE_MEMITEM_SROUCE_FAILED", "销单失败，更新项目套餐数据失败"),
	BILL_CANCEL_UPDATE_PRODUCT_INVENTORY_FAILED("BILL_CANCEL_UPDATE_CARD_SROUCE_FAILED", "销单失败，更新库存数据失败"),
	
	/*
	 * 预约
	 */
	RESERVATION_INVALID_STATUS("RESERVATION_INVALID_STATUS","操作失败，预约状态异常"),
	RESERVATION_TIME_CONFLICT("RESERVATION_TIME_CONFLICT","操作失败，该时间已经有其他顾客预约"),
	RESERVATION_VACATION_CONFLICT("RESERVATION_VACATION_CONFLICT","操作失败，员工当天休假"),
	
	/*
	 * 账号
	 */
	ACCOUNT_EXIST("ACCOUNT_EXIST", "账号已存在"),
	
	/*
	 * 商户
	 */
	SHOP_NOT_EXIST("SHOP_NOT_EXIST", "商城不存在"),
	
	/*
	 * 运营系统
	 */
	CITY_AREAID_EXIST("CITY_AREAID_EXIST", "城市区号已存在"),
	
	/*
	 * 部门及员工级别
	 */
	DEPARTMENT_EXIST("DEPARTMENT_EXIST", "部门已存在"),
	EMPGRADE_EXIST("EMPGRADE_EXIST", "员工级别已存在");
	
	private final String code;
	private final String msg;

	MsgCode(String code, String msg) {
		this.code = code;
		this.msg = msg;
	}

	public String getCode() {
		return code;
	}

	public String getMsg() {
		return msg;
	}

}
